package co.codewizards.cloudstore.rest.client.ssl;

public interface DynamicX509TrustManagerCallback {

	CheckServerTrustedCertificateExceptionResult handleCheckServerTrustedCertificateException(CheckServerTrustedCertificateExceptionContext context);

}
